name: quiz
description: "A Quiz app using Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  animate_do: ^2.0.0
  smooth_page_indicator: ^1.1.0
  nb_utils: ^6.1.0
  dots_indicator: ^2.0.0
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.0.12
  cached_network_image: ^3.1.0
  flutter_staggered_grid_view: ^0.4.1
  html: ^0.15.0
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  connectivity_plus_web: ^1.2.5
  path_provider_windows: ^2.2.1
  shared_preferences_windows: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# ✅ This section forces newer, web-compatible versions
dependency_overrides:
  web: ^1.1.0
  connectivity_plus_web: ^1.2.5
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true

  assets:
    - images/quiz/
    - images/quiz/quiz_logo.jpg
